@echo off
setlocal
cd /d "%~dp0..\Server-Python"
set OPENAI_MODEL=gpt-4.1-mini
set OPENAI_NANO_MODEL=gpt-4.1-nano
set OPENAI_ROUTING_ENABLED=1
set OPENAI_TIMEOUT_SECONDS=8.0
set OPENAI_MAX_OUTPUT_TOKENS=130
set OPENAI_NANO_MAX_OUTPUT_TOKENS=110
set OPENAI_TEMPERATURE=0.55
set OPENAI_NANO_TEMPERATURE=0.75
set OPENAI_MAX_CONCURRENCY=8
set OPENAI_NANO_MAX_CONCURRENCY=8
set OPENAI_STT_MODEL=gpt-4o-mini-transcribe
set OPENAI_STT_TIMEOUT_SECONDS=4.0
set STT_PROVIDER_MAX_CONCURRENCY=8
set STT_MAX_IN_FLIGHT=64
set STT_MAX_AUDIO_BYTES=5242880
set RUNTIME_OPENAI_HISTORY_TURNS=20
set RUNTIME_MAX_IN_FLIGHT=64
set RUNTIME_ASYNC_MAX_IN_FLIGHT=64
set RUNTIME_TURN_ASYNC_MAX_IN_FLIGHT=64
set RUNTIME_PROVIDER_TIMEOUT_SECONDS=8.5
set RUNTIME_FALLBACK_TIMEOUT_SECONDS=1.0
set TTS_PROVIDER_MAX_CONCURRENCY=8
set TTS_MAX_IN_FLIGHT=64
set TTS_ASYNC_MAX_IN_FLIGHT=64
python -m uvicorn app.main:app --reload --port 8010
